export default function TermsAndConditionsPage() {
  return (
    <main className="container mx-auto px-4 py-8">
      <div className="prose max-w-4xl mx-auto">
        <h1 className="font-headline text-3xl font-bold mb-5">
          Terms and Conditions
        </h1>
        <p className="mb-6">
          Welcome to <span className="font-bold">Dropped Pin</span>. By
          accessing and using this website, you agree to be bound by the
          following terms and conditions. Please read them carefully. If you do
          not agree with any part of these terms, you should not use this
          website or its services.
        </p>

        <h2 className="font-headline text-2xl font-bold mt-8 mb-5">
          1. Use of the Website
        </h2>
        <p className="mb-6">
          Dropped Pin is a free tool that allows users to retrieve
          geographical coordinates from a dropped pin on a map. You may use
          this tool for personal or business purposes, but you must not misuse
          the site or use it for any illegal or unauthorized activity.
        </p>

        <h2 className="font-headline text-2xl font-bold mt-8 mb-5">
          2. Accuracy of Data
        </h2>
        <p className="mb-6">
          While we strive to provide accurate location data, we do not
          guarantee that the information shown by the tool is 100% precise. The
          coordinates are provided as-is and may depend on third-party APIs and
          services.
        </p>

        <h2 className="font-headline text_2xl font-bold mt-8 mb-5">
          3. Intellectual Property
        </h2>
        <p className="mb-6">
          All content, design, layout, and features on Dropped Pin are the
          property of the website owner. You may not copy, reproduce, or
          distribute any part of the website without prior written permission.
        </p>

        <h2 className="font-headline text-2xl font-bold mt-8 mb-5">
          4. Limitation of Liability
        </h2>
        <p className="mb-6">
          We shall not be held liable for any direct or indirect damage, loss
          of data, or issues arising from the use of this tool or website.
          Users assume full responsibility for any action taken using the
          location data generated by this tool.
        </p>

        <h2 className="font-headline text-2xl font-bold mt-8 mb-5">
          5. External Links
        </h2>
        <p className="mb-6">
          This website may contain links to other websites. We are not
          responsible for the content or practices of those third-party sites
          and encourage users to review their respective terms and policies.
        </p>

        <h2 className="font-headline text-2xl font-bold mt-8 mb-5">
          6. Changes to These Terms
        </h2>
        <p className="mb-6">
          We may update these Terms and Conditions at any time without prior
          notice. Continued use of the site signifies your acceptance of any
          new or modified terms.
        </p>

        <h2 className="font-headline text-2xl font-bold mt-8 mb-5">
          7. Contact Information
        </h2>
        <p className="mb-6">
          For any questions regarding these Terms and Conditions, please
          contact us.
        </p>
      </div>
    </main>
  );
}
